spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://binukaboss:Binuka2003@cluster0.2cfiu.mongodb.net/Smart_Schooler?retryWrites=true&w=majority&appName=Cluster0


spring.secrity.oauth2.client.registration.google.client-id=362891306384-gsfipl61o1pttkhoo8cci2auqniu4k3f.apps.googleusercontent.com
spring.secrity.oauth2.client.registration.google.client-secret=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
spring.secrity.oauth2.client.registration.google.client.scope=